//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Importador.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.10.0.0")]
    internal sealed partial class Configuracoes : global::System.Configuration.ApplicationSettingsBase {
        
        private static Configuracoes defaultInstance = ((Configuracoes)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Configuracoes())));
        
        public static Configuracoes Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Configuracao\\imp.db")]
        public string BancoLocal {
            get {
                return ((string)(this["BancoLocal"]));
            }
            set {
                this["BancoLocal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CodigoImplantacao {
            get {
                return ((string)(this["CodigoImplantacao"]));
            }
            set {
                this["CodigoImplantacao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"SELECT @as Codigo, @as tipo, @as RazaoSocial, @as NomeFantasia, @as Endereco, @as Bairro, @as Cidade, @as UF, @as CEP, @as codigocidadeibge, @as numero, @as complemento, @as telefone1, @as telefone2, @as fax, @as DataNascimento, @as CNPJ, @as IE, @as CPF, @as RG, @as ValorCredito, @as email, @as FisicaJuridica, @as contato, @'IMPORTACAO' as usuario, @'IMPORTACAO' AS terminal, @0 as EmpresaCadastro @FROM CLIENTES;")]
        public string sqlClientes {
            get {
                return ((string)(this["sqlClientes"]));
            }
            set {
                this["sqlClientes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"SELECT @as Codigo, @ as Descricao, @ as detalhamento, @ as referencia, @ as codigobarras, @ as UNVenda, @ as ValorCusto, @(custofinal - valorcusto) as outroscustos, @ as custofinal, @ as VendaT1, @ as cst_simples, @ as codigocf, @ as ncm, @ as cest, @ as CodigoFabricante, @ as fabricante, @ as CodigoSecao, @ as Secao, @ as CodigoGrupo, @ as grupo, @ as CodigoSubGrupo, @ as SubGrupo, @'Revenda' as TipoProduto , @'Normal' as ModalidadeControle, @'IMPORTACAO' as Usuario, @'IMPORTACAO' as Terminal, @ AS cst_pis, @ AS Cst_Cofins, @ AS aliq_COFINS, @ AS aliq_pis, @ AS BaseCalculoICMS, @ AS AliquotaICMS @FROM PRODUTOS")]
        public string sqlProdutos {
            get {
                return ((string)(this["sqlProdutos"]));
            }
            set {
                this["sqlProdutos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT @ascodigoproduto, @asuf, @asMVA, @asMVA_AJUST , @asMVA_SIMPLES , @asICMS ," +
            " @asICMS_Intra , @asICMS_Inter_PF , @asCST , @asCST_Simples , @asValorPauta, @as" +
            "Empresa , @asBaseST @FROM produtos_st;")]
        public string sqlProdutosST {
            get {
                return ((string)(this["sqlProdutosST"]));
            }
            set {
                this["sqlProdutosST"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"SELECT @ AS codigo, @ AS razaosocial, @ AS ndocumento, @ AS datalancamento, @ AS vencimento, @ AS vencimentooriginal, @ AS valor, @ AS valorpago, @ AS valorpendente, @ AS quitado, @ AS dataquitacao, @ AS juro, @ AS desconto, @ AS quantidadepagamentos, @ AS npagamento, @ AS descricao, @0 AS empresa, @ AS valororiginal, @'IMPORTACAO' AS usuario, @'IMPORTACAO' AS terminal, @1 AS CodModalidade, @'CARTEIRA' AS Modalidade @ FROM CONTASAPAGAR")]
        public string sqlContasAPagar {
            get {
                return ((string)(this["sqlContasAPagar"]));
            }
            set {
                this["sqlContasAPagar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"SELECT @ AS codigo, @ AS razaosocial, @ AS ndocumento, @ AS datalancamento, @ AS vencimento, @ AS vencimentooriginal, @ AS valor, @ AS valorpago, @ AS valorpendente, @ AS quitado, @ AS dataquitacao, @ AS juro, @ AS desconto, @ AS quantidadepagamentos, @ AS npagamento, @ AS descricao, @0 AS empresa, @ AS valororiginal, @'IMPORTACAO' AS usuario, @'IMPORTACAO' AS terminal, @1 AS CodModalidade, @'CARTEIRA' AS Modalidade @ FROM contasareceber")]
        public string sqlContasAReceber {
            get {
                return ((string)(this["sqlContasAReceber"]));
            }
            set {
                this["sqlContasAReceber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT @ as Codigo, @ as Descricao, @ as ValorCusto, @ as valorvenda, @ as servic" +
            "oterceiro, @\'g\' as status, @1 as ativo, @ as DescontoMaximo @ FROM servicos")]
        public string sqlServicos {
            get {
                return ((string)(this["sqlServicos"]));
            }
            set {
                this["sqlServicos"] = value;
            }
        }
    }
}
