//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Importador.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.10.0.0")]
    internal sealed partial class SQLPadrao : global::System.Configuration.ApplicationSettingsBase {
        
        private static SQLPadrao defaultInstance = ((SQLPadrao)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SQLPadrao())));
        
        public static SQLPadrao Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"SELECT @as Codigo, @as tipo, @as RazaoSocial, @as NomeFantasia, @as Endereco, @as Bairro, @as Cidade, @as UF, @as CEP, @as codigocidadeibge, @as numero, @as complemento, @as telefone1, @as telefone2, @as fax, @as DataNascimento, @as CNPJ, @as IE, @as CPF, @as RG, @as ValorCredito, @as email, @as FisicaJuridica, @as contato, @'IMPORTACAO' as usuario, @'IMPORTACAO' AS terminal, @0 as EmpresaCadastro, @as Status, @as CodigoImportacaoDados @FROM CLIENTES;")]
        public string clientes {
            get {
                return ((string)(this["clientes"]));
            }
            set {
                this["clientes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"SELECT @as Codigo, @ as Descricao, @ as detalhamento, @ as referencia, @ as codigobarras, @ as UNVenda, @ as ValorCusto, @(custofinal - valorcusto) as outroscustos, @ as custofinal, @ as VendaT1, @ as cst_simples, @ as codigocf, @ as ncm, @ as cest, @ as CodigoFabricante, @ as fabricante, @ as CodigoSecao, @ as Secao, @ as CodigoGrupo, @ as grupo, @ as CodigoSubGrupo, @ as SubGrupo, @'Revenda' as TipoProduto , @'Normal' as ModalidadeControle, @'IMPORTACAO' as Usuario, @'IMPORTACAO' as Terminal, @ AS cst_pis, @ AS Cst_Cofins, @ AS aliq_COFINS, @ AS aliq_pis, @ AS BaseCalculoICMS, @ AS AliquotaICMS, @as Cancelado, @as CodigoImportacaoDados @FROM PRODUTOS")]
        public string produtos {
            get {
                return ((string)(this["produtos"]));
            }
            set {
                this["produtos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT @as codigoproduto, @as uf, @as MVA, @as MVA_AJUST , @as MVA_SIMPLES , @as " +
            "ICMS , @as ICMS_Intra , @as ICMS_Inter_PF , @as CST , @as CST_Simples , @as Valo" +
            "rPauta, @as Empresa , @as BaseST @FROM produtos_st;")]
        public string produtos_st {
            get {
                return ((string)(this["produtos_st"]));
            }
            set {
                this["produtos_st"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"SELECT @ AS codigo, @ AS razaosocial, @ AS ndocumento, @ AS datalancamento, @ AS vencimento, @ AS vencimentooriginal, @ AS valor, @ AS valorpago, @ AS valorpendente, @ AS quitado, @ AS dataquitacao, @ AS juro, @ AS desconto, @ AS quantidadepagamentos, @ AS npagamento, @ AS descricao, @1 AS empresa, @ AS valororiginal, @'IMPORTACAO' AS usuario, @'IMPORTACAO' AS terminal, @1 AS CodModalidade, @'CARTEIRA' AS Modalidade @ FROM CONTASAPAGAR")]
        public string contasapagar {
            get {
                return ((string)(this["contasapagar"]));
            }
            set {
                this["contasapagar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"SELECT @ AS codigo, @ AS razaosocial, @ AS ndocumento, @ AS datalancamento, @ AS vencimento, @ AS vencimentooriginal, @ AS valor, @ AS valorpago, @ AS valorpendente, @ AS quitado, @ AS dataquitacao, @ AS juro, @ AS desconto, @ AS quantidadepagamentos, @ AS npagamento, @ AS descricao, @1 AS empresa, @ AS valororiginal, @'IMPORTACAO' AS usuario, @'IMPORTACAO' AS terminal, @1 AS CodModalidade, @'CARTEIRA' AS Modalidade @ FROM contasareceber")]
        public string contasareceber {
            get {
                return ((string)(this["contasareceber"]));
            }
            set {
                this["contasareceber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT @ as Codigo, @ as Descricao, @ as ValorCusto, @ as valorvenda, @ as servic" +
            "oterceiro, @\'g\' as status, @1 as ativo, @ as DescontoMaximo @ FROM servicos")]
        public string servicos {
            get {
                return ((string)(this["servicos"]));
            }
            set {
                this["servicos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("acertoestoque auditoriaestoque cidades clientes contasapagar contasareceber fabri" +
            "cantes grupos produtos produtosestoque secoes subgrupos unidades")]
        public string backup {
            get {
                return ((string)(this["backup"]));
            }
            set {
                this["backup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("select @  as codigo, @  as descricao @from secoes")]
        public string secoes {
            get {
                return ((string)(this["secoes"]));
            }
            set {
                this["secoes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("select @  as codigo, @  as descricao, @  as codigosecao, @  as descricaosecao @fr" +
            "om grupos")]
        public string grupos {
            get {
                return ((string)(this["grupos"]));
            }
            set {
                this["grupos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("select @  as codigo, @  as descricao, @  as codigogrupo, @  as descricaogrupo @fr" +
            "om subgrupos")]
        public string subgrupos {
            get {
                return ((string)(this["subgrupos"]));
            }
            set {
                this["subgrupos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("select @  as codigo, @  as descricao @from fabricantes")]
        public string fabricantes {
            get {
                return ((string)(this["fabricantes"]));
            }
            set {
                this["fabricantes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("select @  as codigoproduto,@  as estoque,@  as empresa,@  curdate() as DataUltima" +
            "Mov,@  \'MASTER\' as Usuario @from produtosestoque")]
        public string produtosestoque {
            get {
                return ((string)(this["produtosestoque"]));
            }
            set {
                this["produtosestoque"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("select @  as idprodutos,@  as idfornecedor@from produtosfornecedor")]
        public string produtosfornecedor {
            get {
                return ((string)(this["produtosfornecedor"]));
            }
            set {
                this["produtosfornecedor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("select @  as codigoproduto,@  as barcode,@  as fracionario,@  as grade_linha,@  a" +
            "s grade_coluna,@  as idgrade@from produtosbarcode")]
        public string produtosbarcode {
            get {
                return ((string)(this["produtosbarcode"]));
            }
            set {
                this["produtosbarcode"] = value;
            }
        }
    }
}
